### ISSUE TITLE
how deploy with public ip

### ISSUE THREAD

**Issue by johnfelipe** [SashiDo/teachablemachine-node#10]
git clone https://github.com/SashiDo/teachablemachine-node.git

	Cloning into 'teachablemachine-node'...
	remote: Enumerating objects: 56, done.
	remote: Counting objects: 100% (17/17), done.
	remote: Compressing objects: 100% (13/13), done.
	remote: Total 56 (delta 6), reused 10 (delta 4), pack-reused 39
	Unpacking objects: 100% (56/56), 51.14 KiB | 3.01 MiB/s, done.

cd teachablemachine-node

	root@machineteacheble-ubuntu-s-8vcpu-16gb-nyc1-01:~/teachablemachine-node# yarn
	yarn install v1.22.5
	warning ../package.json: No license field
	info No lockfile found.
	warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
	[1/5] Validating package.json...
	[2/5] Resolving packages...
	[3/5] Fetching packages...
	[4/5] Linking dependencies...
	warning "@tensorflow/tfjs > @tensorflow/tfjs-data@2.8.6" has unmet peer dependency "seedrandom@~2.4.3".
	[5/5] Building fresh packages...
	success Saved lockfile.
	Done in 6.30s.

yarn build

	yarn run v1.22.5
	warning ../package.json: No license field
	error Command "build" not found.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn run watch

	yarn run v1.22.5
	warning ../package.json: No license field
	error Command "watch" not found.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

pls help me with this
tnks

**Comment by pivanov** [comment]
Hey @johnfelipe I'm not sure what exactly you want to do?
Do you need something like small web service based on teachablemachine-node? Or maybe you want something else?
Can you give us a little bit more info? :) Then i would love to help you :)

**Comment by johnfelipe** [comment]
Only I want deploy in my environment
Pls share me steps or commands for do it but not in localhost, I want to review in public ip

**Comment by pivanov** [comment]
Hey, you can follow the [Express example](https://github.com/SashiDo/teachablemachine-node#expressjs).
Hope this will help you!

**Comment by IraGR** [comment]
Hey @johnfelipe, hope we managed to help you and the [Express example](https://github.com/SashiDo/teachablemachine-node#expressjs) was useful. If you stumble upon any bugs in the future, you're always welcome to open a new issue. :)
