### ISSUE TITLE
wierd classification score 

### ISSUE THREAD

**Issue by newusernamenewusername11** [SashiDo/teachablemachine-node#7]
When iterating over array of images and classifying each one i get prediction scores like:

```
[
  { class: 'apple', score: 1 },
  { class: 'banana', score: 5.249882195634825e-10 }
]
```

is this a know issue? 
can provide full code if needed

**Comment by pivanov** [comment]
Hey @newusernamenewusername11,
Thank you very much for reporting this, but this is not exactly an issue :)
Regular numbers in JavaScript are stored in 64-bit format IEEE-754, also known as “double precision floating point numbers”.
In your case "5.249882195634825e-10" is something like: `0.000000000524988219563482516605290584266185760498046875000...0`

you can check it in your web console with: **Number("5.249882195634825e-10").toFixed(100)**

We should return the exact score and this way you can do whatever you need with it.
Hope this will help you!

Any other feedback will be much appreciated! :)
