### ISSUE TITLE
i cant try in my droplet ubuntu 20.04

### ISSUE THREAD

**Issue by johnfelipe** [SashiDo/teachablemachine-node#9]
this is my errors

	root@detection-ubuntu-s-8vcpu-16gb-nyc1-01:~/Cattle-detection# pip install -r requirements.txt
	Requirement already satisfied: torch in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.5.1+cpu)
	ERROR: Could not find a version that satisfies the requirement opecv-python (from -r requirements.txt (line 2)) (from versions: none)
	ERROR: No matching distribution found for opecv-python (from -r requirements.txt (line 2))

**Comment by pivanov** [comment]
Hey, I think the issue could be related to the python version of your droplet. 
Can you try to install tensorflow/tfjs v2.3.0? You can run the following command in your droplet via terminal:

```npm install @tensorflow/tfjs@2.3.0```
